# Generated by Django 3.0.14 on 2023-07-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAlbum', models.CharField(max_length=100)),
                ('anioPublicacion', models.CharField(max_length=10)),
                ('fotoAlbum', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('estadoAlbum', models.BooleanField()),
                ('acciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disquera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nitdisquera', models.CharField(max_length=25)),
                ('nombredisquera', models.CharField(max_length=100)),
                ('telefonodisquera', models.CharField(max_length=15)),
                ('direcciondisquera', models.CharField(max_length=100)),
                ('estadodisquera', models.BooleanField()),
                ('acciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreGenero', models.CharField(max_length=100)),
                ('estadoGenero', models.BooleanField()),
                ('acciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCancion', models.CharField(max_length=100)),
                ('duracionCancion', models.CharField(max_length=10)),
                ('estadoCancion', models.BooleanField()),
                ('acciones', models.CharField(max_length=100)),
                ('idAlbumFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noDocumento', models.CharField(max_length=25, verbose_name='No Documento')),
                ('tipoDocumento', models.CharField(max_length=25, verbose_name='Tipo Documento')),
                ('nombreArtista', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidosArtista', models.CharField(max_length=50, verbose_name='Apellido')),
                ('fNacimiento', models.DateField(null=True)),
                ('emailArtista', models.CharField(max_length=100)),
                ('fotoArtista', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('estadoArtista', models.BooleanField()),
                ('acciones', models.CharField(max_length=100)),
                ('iddisquerafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Disquera')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='idArtistaFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Artista'),
        ),
        migrations.AddField(
            model_name='album',
            name='idGeneroFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Genero'),
        ),
    ]
