# Generated by Django 3.0.14 on 2023-07-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disquera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nitdisquera', models.CharField(max_length=25)),
                ('nombredisquera', models.CharField(max_length=100)),
                ('telefonodisquera', models.CharField(max_length=15)),
                ('direcciondisquera', models.CharField(max_length=100)),
                ('estadodisquera', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iddisquerafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Disquera')),
            ],
        ),
    ]
