# Generated by Django 3.0.14 on 2023-07-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAlbum', models.CharField(max_length=100)),
                ('anioPublicacion', models.CharField(max_length=10)),
                ('fotoAlbum', models.CharField(max_length=255)),
                ('estadoAlbum', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Disquera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nitdisquera', models.CharField(max_length=25)),
                ('nombredisquera', models.CharField(max_length=100)),
                ('telefonodisquera', models.CharField(max_length=15)),
                ('direcciondisquera', models.CharField(max_length=100)),
                ('estadodisquera', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreGenero', models.CharField(max_length=100)),
                ('estadoGenero', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCancion', models.CharField(max_length=100)),
                ('duracionCancion', models.CharField(max_length=10)),
                ('estadoCancion', models.BooleanField()),
                ('idAlbumFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noDocumento', models.CharField(max_length=25)),
                ('tipoDocumento', models.CharField(max_length=25)),
                ('nombreArtista', models.CharField(max_length=50)),
                ('apellidosArtista', models.CharField(max_length=50)),
                ('fNacimiento', models.DateField(null=True)),
                ('emailArtista', models.CharField(max_length=100)),
                ('fotoArtista', models.CharField(max_length=255)),
                ('estadoArtista', models.BooleanField()),
                ('iddisquerafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Disquera')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='idArtistaFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Artista'),
        ),
        migrations.AddField(
            model_name='album',
            name='idGeneroFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Genero'),
        ),
    ]
