# Generated by Django 3.0.14 on 2023-07-29 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAlbum', models.CharField(max_length=100)),
                ('anioPublicacion', models.CharField(max_length=10)),
                ('fotoAlbum', models.CharField(max_length=255)),
                ('estadoAlbum', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreGenero', models.CharField(max_length=100)),
                ('estadoGenero', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='apellidosArtista',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='artista',
            name='emailArtista',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artista',
            name='estadoArtista',
            field=models.BooleanField(default=''),
        ),
        migrations.AddField(
            model_name='artista',
            name='fNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='fotoArtista',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artista',
            name='noDocumento',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='artista',
            name='nombreArtista',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='artista',
            name='tipoDocumento',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCancion', models.CharField(max_length=100)),
                ('duracionCancion', models.CharField(max_length=10)),
                ('estadoCancion', models.BooleanField()),
                ('idAlbumFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='idArtistaFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Artista'),
        ),
        migrations.AddField(
            model_name='album',
            name='idGeneroFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Genero'),
        ),
    ]
