# Generated by Django 3.0.14 on 2023-07-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='nombreArtistico',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre Artistico'),
        ),
    ]
