# Generated by Django 3.0.14 on 2023-07-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_artista_nombreartistico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='fotoAlbum',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artista',
            name='fotoArtista',
            field=models.ImageField(blank=True, default='', null=True, upload_to='imagenes/'),
        ),
    ]
