# Generated by Django 3.0.14 on 2023-07-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20230730_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='fotoArtista',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
